# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "96c6146632a0dd1b8b370411031217bf"
application_url = "https://connected-smtp-led-lounge.trycloudflare.com"
embedded = true
name = "CSV Custom Fields"
handle = "bulk-app-12"

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders,read_customers"

[auth]
redirect_urls = [
  "https://connected-smtp-led-lounge.trycloudflare.com/auth/callback",
  "https://connected-smtp-led-lounge.trycloudflare.com/auth/shopify/callback",
  "https://connected-smtp-led-lounge.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "asya-test-store.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
